<a href="https://colab.research.google.com/github/andrerizzo/complete_project/blob/code/Modelagem_with_Bayesian_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold


In [3]:
# Import dataset
url1 = 'https://raw.githubusercontent.com/andrerizzo/complete_project/dataset/iris_predictors.csv'
url2 = 'https://raw.githubusercontent.com/andrerizzo/complete_project/dataset/iris_response.csv'
X = pd.read_csv(url1)
y = pd.read_csv(url2)

print(X)
print(y)

     sepal_width  petal_length_trans
0            3.0           -1.222611
1            3.2           -1.641609
2            3.1           -0.860957
3            3.6           -1.222611
4            3.9           -0.518618
..           ...                 ...
144          3.0            0.767216
145          2.5            0.537961
146          3.0            0.767216
147          3.4            0.860957
148          3.0            0.658733

[149 rows x 2 columns]
              class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
144  Iris-virginica
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica

[149 rows x 1 columns]


In [4]:
# Handling Categorical Variables

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y = encoder.fit_transform(y.values.ravel())

print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [5]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

     sepal_width  petal_length_trans
27           3.4           -1.222611
97           2.5           -0.433806
96           2.9           -0.025237
69           3.2            0.369964
18           3.8           -0.860957
..           ...                 ...
9            3.7           -0.860957
103          3.0            1.297001
67           2.2            0.126509
117          2.6            2.710835
47           3.7           -0.860957

[119 rows x 2 columns]
     sepal_width  petal_length_trans
133          2.6            1.046561
109          3.2            0.658733
59           2.0           -0.369964
80           2.4           -0.325284
7            2.9           -1.222611
104          3.0            1.986482
140          3.1            0.658733
95           2.9           -0.075776
118          2.2            0.537961
84           3.4            0.126509
33           3.1           -0.860957
44           3.0           -1.222611
54           2.8            0.126509
24           3

In [6]:
# Create dictionary to store accuracy results
results = {}

In [7]:
# Evaluate Models - LDA

# Import libraries
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = LDA()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Linear Discriminant Analysis model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['LDA'] = np.mean(scores)

Linear Discriminant Analysis model accuracy: 0.913 (0.095) 



In [ ]:
# Evaluate Models - kNN

# Import libraries
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = KNeighborsClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores= 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("k-Nearest Neighbors model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['kNN'] = np.mean(scores)

In [11]:
# Evaluate Models - SVC

# Import libraries
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = SVC(kernel='linear')

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Support Vector Classifier model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['SVC'] = np.mean(scores)

Support Vector Classifier model accuracy: 0.941 (0.084) 



In [ ]:
# Evaluate Models - SGD

# Import libraries
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = SGDClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Stochastic Gradient Descend model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['SGD'] = np.mean(scores)

In [ ]:
# Evaluate Models - Gaussian Naive Bayes

# Import libraries
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = GaussianNB()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Naive Bayes model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['Gaussian Naive Bayes'] = np.mean(scores)

In [ ]:
# Evaluate Models - Decision Tree

# Import libraries
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = DecisionTreeClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Decision Tree Classifier model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['Decision Trees'] = np.mean(scores)

In [ ]:
# Evaluate Models - Random Forest

# Import libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = RandomForestClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1, error_score='raise')

print("Random Forerst model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['Random Forest'] = np.mean(scores)

In [ ]:
# Evaluate Models - AdaBoost

# Import libraries
from sklearn.ensemble import AdaBoostClassifier

# Define model
classifier = AdaBoostClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1, error_score='raise')

print("AdaBoost model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['AdaBoost'] = np.mean(scores)

In [ ]:
# Evaluate Models - MLP Classifier

# Import libraries
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

# Define model
classifier = MLPClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Multi-Layer Perceptron Model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['MLP Classifier'] = np.mean(scores)

In [ ]:
# Show results

results = sorted(results.items(), reverse=True, key=lambda item: item[1])
results

In [9]:
# Hyperparameter tuning - SVC
from skopt import BayesSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.svm import SVC

# define search space
hparams = dict()
hparams['C'] = (1e-6, 100.0, 'log-uniform')
hparams['gamma'] = (1e-6, 100.0, 'log-uniform')
hparams['degree'] = (1,5)
hparams['kernel'] = ['linear', 'poly', 'rbf', 'sigmoid']

# Define evaluation
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Define the search
search = BayesSearchCV(estimator=SVC(), search_spaces=hparams, n_jobs=-1, cv=cv)

# Perform the search
search.fit(X_train, y_train)

# Store result
SVC_hyper_result = search.best_params_

# Report best result
print("Best hyperparameters:")
print(SVC_hyper_result, "\n")
print("SVC model accuracy after best hyperparameter definition: %.3f" % (search.best_score_))

Best hyperparameters:
OrderedDict([('C', 1.0872838969479126), ('degree', 1), ('gamma', 100.0), ('kernel', 'linear')]) 

SVC model accuracy after best hyperparameter definition: 0.944


In [10]:
# Hyperparameter tuning - Random Forest (using tune_sklearn)

from tune_sklearn import TuneSearchCV
from sklearn.ensemble import RandomForestClassifier as RFC

# define search space
hparams = dict()
hparams['n_estimators'] = (1, 1000, 'uniform')
hparams['criterion'] = ['gini', 'entropy']
hparams['max_depth'] = (1,100, "uniform")
hparams['min_samples_split'] = (1e-10, 9e-10, "log-uniform")
hparams['min_samples_leaf'] = (1e-6, 0.5, "log-uniform")
hparams['min_weight_fraction_leaf'] = (0, 0.5, "log-uniform")
hparams['max_features'] = ['auto', 'sqrt', 'log2']
hparams['max_leaf_nodes'] = (1,100, "uniform")
hparams['min_impurity_decrease'] = (1e-6, 1e10, "log-uniform")
#hparams['bootstrap'] = (True, False)
hparams['oob_score'] = (True, False)
#hparams['n_jobs'] = (-1, 1)
hparams['class_weight'] = ('balanced', 'balanced_subsample')
hparams['ccp_alpha'] = (1e-6, 1e10, "log-uniform")


# Define evaluation
#cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Define the search
tune_search = TuneSearchCV(RFC(),
                           param_distributions = hparams,
                           use_gpu = False,
                           cv = 10,
                           n_jobs = 1,
                           search_optimization = 'bayesian',
                           refit = True,
                           verbose=0,
                           random_state=1
                          )
                      
# Perform the search
tune_search.fit(X_train, y_train.values.ravel())

# Report best result
print("Best hyperparameters:")
print(tune_search.best_params_, "\n")
print("Random Forest model accuracy after best hyperparameter definition: %.3f" % (tune_search.best_score_))

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [ ]:
# Hyperparameter tuning - LDA (using tune_sklearn)

from tune_sklearn import TuneSearchCV
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA


# define search space
hparams = dict()
hparams['solver'] = ['lsqr', 'eigen']
hparams['shrinkage'] = (None,'auto')
#hparams['n_components'] = (1, 2)
hparams['tol'] = (1e-6, 1e10, "log-uniform")


# Define evaluation
#cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Define the search
tune_search = TuneSearchCV(LDA(),
                           param_distributions = hparams,
                           use_gpu = False,
                           cv = 10,
                           n_jobs = 1,
                           search_optimization = 'bayesian',
                           refit = True,
                           verbose=0, 
                           random_state=1
                          )
                      
# Perform the search
tune_search.fit(X_train, y_train.values.ravel())

# Report the best result
print(tune_search.best_params_)

print("Multi-Layer Perceptron Model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)))


In [15]:
# Train SVC model using computed hyperparameters

from sklearn.svm import SVC
import sklearn.metrics as clf_metrics


# Defining model with hyperparameters
model = SVC(C = SVC_hyper_result["C"], 
            kernel = SVC_hyper_result["kernel"],
            degree = SVC_hyper_result["degree"],
            gamma = SVC_hyper_result["gamma"],
           )

# Fitting model to train set
model.fit(X_train, y_train)

# Predicting with testing set
y_pred = model.predict(X_test)

#clf_metrics.auc(y_test, y_pred)

# Show metrics
print('Confusion matrix')
print(clf_metrics.confusion_matrix(y_test, y_pred),"\n")
print('Accuracy score:', clf_metrics.accuracy_score(y_test, y_pred),"\n")
print('Class weights')
print(model.class_weight_)


Confusion matrix
[[12  0  0]
 [ 0 10  0]
 [ 0  0  8]] 

Accuracy score: 1.0 

Class weights
[1. 1. 1.]


In [ ]:
# Train kNN model using computed hyperparameters

