<a href="https://colab.research.google.com/github/andrerizzo/complete_project/blob/code/Modelagem_with_Bayesian_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold


In [2]:
# Import dataset
url1 = 'https://raw.githubusercontent.com/andrerizzo/complete_project/dataset/iris_predictors.csv'
url2 = 'https://raw.githubusercontent.com/andrerizzo/complete_project/dataset/iris_response.csv'
X = pd.read_csv(url1)
y = pd.read_csv(url2)

print(X)
print(y)

     sepal_width  petal_length_trans
0            3.0           -1.222611
1            3.2           -1.641609
2            3.1           -0.860957
3            3.6           -1.222611
4            3.9           -0.518618
..           ...                 ...
144          3.0            0.767216
145          2.5            0.537961
146          3.0            0.767216
147          3.4            0.860957
148          3.0            0.658733

[149 rows x 2 columns]
              class
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
144  Iris-virginica
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica

[149 rows x 1 columns]


In [3]:
# Handling Categorical Variables

from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
iris_class_encoded = encoder.fit_transform(y.values.ravel())

from sklearn.preprocessing import OneHotEncoder
hot_encoder = OneHotEncoder()
y_hot_encoded = hot_encoder.fit_transform(iris_class_encoded.reshape(-1,1))
#y = y.toarray()
print(y_hot_encoded)

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 0)	1.0
  (21, 0)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 0)	1.0
  :	:
  (124, 2)	1.0
  (125, 2)	1.0
  (126, 2)	1.0
  (127, 2)	1.0
  (128, 2)	1.0
  (129, 2)	1.0
  (130, 2)	1.0
  (131, 2)	1.0
  (132, 2)	1.0
  (133, 2)	1.0
  (134, 2)	1.0
  (135, 2)	1.0
  (136, 2)	1.0
  (137, 2)	1.0
  (138, 2)	1.0
  (139, 2)	1.0
  (140, 2)	1.0
  (141, 2)	1.0
  (142, 2)	1.0
  (143, 2)	1.0
  (144, 2)	1.0
  (145, 2)	1.0
  (146, 2)	1.0
  (147, 2)	1.0
  (148, 2)	1.0


In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

     sepal_width  petal_length_trans
27           3.4           -1.222611
97           2.5           -0.433806
96           2.9           -0.025237
69           3.2            0.369964
18           3.8           -0.860957
..           ...                 ...
9            3.7           -0.860957
103          3.0            1.297001
67           2.2            0.126509
117          2.6            2.710835
47           3.7           -0.860957

[119 rows x 2 columns]
     sepal_width  petal_length_trans
133          2.6            1.046561
109          3.2            0.658733
59           2.0           -0.369964
80           2.4           -0.325284
7            2.9           -1.222611
104          3.0            1.986482
140          3.1            0.658733
95           2.9           -0.075776
118          2.2            0.537961
84           3.4            0.126509
33           3.1           -0.860957
44           3.0           -1.222611
54           2.8            0.126509
24           3

In [5]:
# Create dictionary to store accuracy results
results = {}

In [6]:
# Evaluate Models - LDA

# Import libraries
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

# Define model
classifier = LDA()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X_train, y_train, cv=cv, scoring='accuracy', n_jobs=-1)

print("Linear Discriminant Analysis model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['LDA'] = np.mean(scores)

Linear Discriminant Analysis model accuracy: 0.913 (0.095) 



In [7]:
# Evaluate Models - kNN

# Import libraries
from sklearn.neighbors import KNeighborsClassifier

# Define model
classifier = KNeighborsClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores= 0
scores = cross_val_score(classifier, X, y, cv=cv, scoring='accuracy', n_jobs=-1)

print("k-Nearest Neighbors model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['kNN'] = np.mean(scores)

k-Nearest Neighbors model accuracy: 0.935 (0.064) 



In [8]:
# Evaluate Models - SVC

# Import libraries
from sklearn.svm import SVC

# Define model
classifier = SVC(kernel='linear')

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X, y, cv=cv, scoring='accuracy', n_jobs=-1)

print("Support Vector Classifier model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['SVC'] = np.mean(scores)

Support Vector Classifier model accuracy: 0.953 (0.055) 



In [9]:
# Evaluate Models - SGD

# Import libraries
from sklearn.linear_model import SGDClassifier

# Define model
classifier = SGDClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X, y, cv=cv, scoring='accuracy', n_jobs=-1)

print("Stochastic Gradient Descend model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['SGD'] = np.mean(scores)

Stochastic Gradient Descend model accuracy: 0.877 (0.097) 



In [10]:
# Evaluate Models - Gaussian Naive Bayes

# Import libraries
from sklearn.naive_bayes import GaussianNB

# Define model
classifier = GaussianNB()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X, y, cv=cv, scoring='accuracy', n_jobs=-1)

print("Naive Bayes model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['Gaussian Naive Bayes'] = np.mean(scores)

Naive Bayes model accuracy: 0.924 (0.054) 



In [11]:
# Evaluate Models - Decision Tree

# Import libraries
from sklearn.tree import DecisionTreeClassifier

# Define model
classifier = DecisionTreeClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X, y, cv=cv, scoring='accuracy', n_jobs=-1)

print("Decision Tree Classifier model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['Decision Trees'] = np.mean(scores)

Decision Tree Classifier model accuracy: 0.917 (0.071) 



In [12]:
# Evaluate Models - Random Forest

# Import libraries
from sklearn.ensemble import RandomForestClassifier

# Define model
classifier = RandomForestClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X, y, cv=cv, scoring='accuracy', n_jobs=-1, error_score='raise')

print("Random Forerst model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['Random Forest'] = np.mean(scores)

Random Forerst model accuracy: 0.944 (0.055) 



In [13]:
# Evaluate Models - AdaBoost

# Import libraries
from sklearn.ensemble import AdaBoostClassifier

# Define model
classifier = AdaBoostClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X, y, cv=cv, scoring='accuracy', n_jobs=-1, error_score='raise')

print("AdaBoost model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['AdaBoost'] = np.mean(scores)

AdaBoost model accuracy: 0.754 (0.111) 



In [14]:
# Evaluate Models - MLP Classifier

# Import libraries
from sklearn.neural_network import MLPClassifier

# Define model
classifier = MLPClassifier()

# Define model evaluation method
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Evaluate model
scores = 0
scores = cross_val_score(classifier, X, y, cv=cv, scoring='accuracy', n_jobs=-1)

print("Multi-Layer Perceptron Model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)), "\n")

# Update dictionary from accuracy results
# results = {}
results['MLP Classifier'] = np.mean(scores)

Multi-Layer Perceptron Model accuracy: 0.946 (0.059) 



In [15]:
# Show results

results = sorted(results.items(), reverse=True, key=lambda item: item[1])
results

[('SVC', 0.9530158730158731),
 ('MLP Classifier', 0.9461904761904764),
 ('Random Forest', 0.943968253968254),
 ('kNN', 0.9349206349206349),
 ('Gaussian Naive Bayes', 0.9236507936507937),
 ('Decision Trees', 0.916984126984127),
 ('LDA', 0.9133838383838384),
 ('SGD', 0.8766666666666668),
 ('AdaBoost', 0.7542857142857144)]

In [16]:
# Hyperparameter tuning - SVC (using tune_sklearn)

# Import libraries
from tune_sklearn import TuneSearchCV
from sklearn.svm import SVC

# Define search space
hparams = dict()
hparams['C'] = (1e-6, 100.0, "log-uniform")
hparams['kernel'] = ['linear', 'poly', 'rbf', 'sigmoid']
hparams['degree'] = (1,5, "uniform")
hparams['gamma'] = (1e-6, 100.0, "log-uniform")
hparams['coef0'] = (1e-6, 100.0, "log-uniform")
hparams['shrinking'] = [True, False]
hparams['tol'] = (1e-6, 100.0, "log-uniform")
hparams['decision_function_shape'] = ['ovo', 'ovr']

# Define the search
tune_search = TuneSearchCV(SVC(),
                           param_distributions = hparams,
                           use_gpu = False,
                           cv = 10,
                           n_jobs = 1,
                           search_optimization = 'bayesian', 
                           random_state = 1                                                        
                          )
                      
# Perform the search
tune_search.fit(X_train, y_train.values.ravel())

# Store result
SVC_hyper_result = tune_search.best_params_

# Report best result
print("Best hyperparameters:")
print(SVC_hyper_result, "\n")
print("SVC model accuracy after best hyperparameter definition: %.3f" % (tune_search.best_score_))

fail_fast='raise' detected. Be careful when using this mode as resources (such as Ray processes, file descriptors, and temporary files) may not be cleaned up properly. To use a safer mode, use fail_fast=True.
Log sync requires rsync to be installed.
Trial Runner checkpointing failed: cannot pickle 'dict_values' object
Trial Runner checkpointing failed: cannot pickle 'dict_values' object


Best hyperparameters:
{'C': 4.333381003524921, 'kernel': 'poly', 'degree': 1, 'gamma': 0.23132593197812873, 'coef0': 0.055529549019350644, 'shrinking': True, 'tol': 0.0019692598741096906, 'decision_function_shape': 'ovo'} 

SVC model accuracy after best hyperparameter definition: 0.942


In [17]:
# Hyperparameter tuning - Random Forest (using tune_sklearn)

from tune_sklearn import TuneSearchCV
from sklearn.ensemble import RandomForestClassifier as RFC

# define search space
hparams = dict()
hparams['n_estimators'] = (1, 1000, 'uniform')
hparams['criterion'] = ['gini', 'entropy']
hparams['max_depth'] = (1,100, "uniform")
hparams['min_samples_split'] = (1e-10, 9e-10, "log-uniform")
hparams['min_samples_leaf'] = (1e-6, 0.5, "log-uniform")
hparams['min_weight_fraction_leaf'] = (0, 0.5, "log-uniform")
hparams['max_features'] = ['auto', 'sqrt', 'log2']
hparams['max_leaf_nodes'] = (1,100, "uniform")
hparams['min_impurity_decrease'] = (1e-6, 1e10, "log-uniform")
#hparams['bootstrap'] = (True, False)
hparams['oob_score'] = (True, False)
#hparams['n_jobs'] = (-1, 1)
hparams['class_weight'] = ('balanced', 'balanced_subsample')
hparams['ccp_alpha'] = (1e-6, 1e10, "log-uniform")


# Define evaluation
#cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Define the search
tune_search = TuneSearchCV(RFC(),
                           param_distributions = hparams,
                           use_gpu = False,
                           cv = 10,
                           n_jobs = 1,
                           search_optimization = 'bayesian',
                           refit = True,
                           verbose=0,
                           random_state=1
                          )
                      
# Perform the search
tune_search.fit(X_train, y_train.values.ravel())

# Report best result
print("Best hyperparameters:")
print(tune_search.best_params_, "\n")
print("Random Forest model accuracy after best hyperparameter definition: %.3f" % (tune_search.best_score_))

C:\Users\andre.rizzo\Anaconda3\lib\site-packages\skopt\space\space.py:502: RuntimeWarning: divide by zero encountered in log10
  np.log10(self.low) / self.log_base,
C:\Users\andre.rizzo\Anaconda3\lib\site-packages\skopt\space\space.py:504: RuntimeWarning: divide by zero encountered in log10
  np.log10(self.low) / self.log_base)
fail_fast='raise' detected. Be careful when using this mode as resources (such as Ray processes, file descriptors, and temporary files) may not be cleaned up properly. To use a safer mode, use fail_fast=True.
Trial Runner checkpointing failed: cannot pickle 'dict_values' object
The `start_trial` operation took 17.556944131851196 seconds to complete, which may be a performance bottleneck.
Trial Runner checkpointing failed: cannot pickle 'dict_values' object
The `start_trial` operation took 4.143283367156982 seconds to complete, which may be a performance bottleneck.
The `start_trial` operation took 38.26698851585388 seconds to complete, which may be a performance

Best hyperparameters:
{'n_estimators': 961, 'criterion': 'entropy', 'max_depth': 99, 'min_samples_split': 4.329215461960729e-10, 'min_samples_leaf': 0.0002358407999271259, 'min_weight_fraction_leaf': 0, 'max_features': 'auto', 'max_leaf_nodes': 7, 'min_impurity_decrease': 2.6047367391637478e-05, 'oob_score': False, 'class_weight': 'balanced_subsample', 'ccp_alpha': 0.02204116122858825} 

Random Forest model accuracy after best hyperparameter definition: 0.925


In [18]:
# Hyperparameter tuning - LDA (using tune_sklearn)

from tune_sklearn import TuneSearchCV
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA


# define search space
hparams = dict()
hparams['solver'] = ['lsqr', 'eigen']
hparams['shrinkage'] = (None,'auto')
#hparams['n_components'] = (1, 2)
hparams['tol'] = (1e-6, 1e10, "log-uniform")


# Define evaluation
#cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# Define the search
tune_search = TuneSearchCV(LDA(),
                           param_distributions = hparams,
                           use_gpu = False,
                           cv = 10,
                           n_jobs = 1,
                           search_optimization = 'bayesian',
                           refit = True,
                           verbose=0, 
                           random_state=1
                          )
                      
# Perform the search
tune_search.fit(X_train, y_train.values.ravel())

# Report the best result
print(tune_search.best_params_)

print("Multi-Layer Perceptron Model accuracy: %.3f (%.3f)" % (np.mean(scores),np.std(scores)))


fail_fast='raise' detected. Be careful when using this mode as resources (such as Ray processes, file descriptors, and temporary files) may not be cleaned up properly. To use a safer mode, use fail_fast=True.
Trial Runner checkpointing failed: cannot pickle 'dict_values' object
The `process_trial` operation took 0.6276142597198486 seconds to complete, which may be a performance bottleneck.
Trial Runner checkpointing failed: cannot pickle 'dict_values' object


{'solver': 'lsqr', 'shrinkage': None, 'tol': 2.2145813425229885}
Multi-Layer Perceptron Model accuracy: 0.946 (0.059)


In [19]:
# Train SVC model using computed hyperparameters

from sklearn.svm import SVC
import sklearn.metrics as clf_metrics


# Defining model with hyperparameters
model = SVC(C = SVC_hyper_result["C"], 
            kernel = SVC_hyper_result["kernel"],
            degree = SVC_hyper_result["degree"],
            gamma = SVC_hyper_result["gamma"],
            coef0 = SVC_hyper_result["coef0"],
            shrinking = SVC_hyper_result["shrinking"], 
            tol = SVC_hyper_result["tol"], 
            decision_function_shape = SVC_hyper_result["decision_function_shape"]
           )

# Fitting model to train set
model.fit(X_train, y_train.values.ravel())

# Predicting with testing set
y_pred = model.predict(X_test)

#clf_metrics.auc(y_test, y_pred)

# Show metrics
print('Confusion matrix')
print(clf_metrics.confusion_matrix(y_test, y_pred),"\n")
print('Accuracy score:', clf_metrics.accuracy_score(y_test, y_pred),"\n")
print('Class weights')
print(model.class_weight_)


Confusion matrix
[[12  0  0]
 [ 0 10  0]
 [ 0  0  8]] 

Accuracy score: 1.0 

Class weights
[1. 1. 1.]


In [20]:
# Train kNN model using computed hyperparameters

